# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ads', models.CharField(max_length=300)),
                ('port', models.IntegerField()),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cmdbci', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceManager.Server'),
        ),
    ]
