# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-17 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('processes', models.ManyToManyField(to='serviceManager.Process')),
            ],
        ),
    ]
